config/routes.rb
Rails.application.routes.draw do
  get '/meals/unselect_diet', to: 'meals#unselect_diet', as: 'unselect_diet'
  get '/meals/:id/select_diet', to: 'meals#select_diet', as: 'select_diet'
  get '/meals/:id/validate', to: 'meals#validate', as: 'validate'
  get '/meals/:id/favorite', to: 'meals#favorite', as: 'favorite'
  resources :meals

  devise_for :users

  root 'pages#index'

  # all your other routes
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  def favorite? user
    unless user
      return nil
    end

    user.meal_id == self.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one :meal
  alias_attribute :meal, :meal_id
  alias_attribute :favorite, :meal
end

app/controllers/application_controller.rb
class CurrentContext
  attr_reader :user, :params

  def initialize(user, params)
    @user = user
    @params = params
  end
end

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Pundit
  # after_action :verify_authorized

  before_action :check_params

  rescue_from ActionController::RoutingError, with: :route_not_found
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from ActiveRecord::AssociationTypeMismatch, with: :request_formed_unproperly
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  before_action :set_current_user
  def set_current_user
    unless current_user
      @current_user ||= nil
      # @current_user ||= doorkeeper_token ? User.find(doorkeeper_token.resource_owner_id) : nil
    end
  end

  def pundit_user
    CurrentContext.new(current_user, params)
  end

  def redirect_to_safe_place
    redirect_to(
      if request.referer and URI(request.referer).path != request.path
        request.referer
      else
        root_path
      end)
  end

  public def route_not_found
    flash[:alert] = "This route does not seems to lead anywhere, sorry for the inconvenience."
    redirect_to_safe_place
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to_safe_place
  end

  def check_params
    types = {
      page: ActionController::Parameters,
      filter: ActionController::Parameters,
      sort: String
    }
    types.each do |parameter, type|
      if params[parameter].present? && !(params[parameter].is_a? type)
        raise ActionController::BadRequest
      end
    end
  end

  def record_not_found
    record_message = "this record"
    record_message = "the #{params["controller"].singularize} with id: #{params["id"]}" if params.key? "controller" and params.key? "id"
    flash[:alert] = "Couldn't find #{record_message}."
    redirect_to_safe_place
  end

  def request_formed_unproperly
    errors = ActiveModel::Errors.new(nil)
    errors.add(:app, I18n.t('errors.bad_request'))
    render json: errors, status: :bad_request and return
  end
end

app/controllers/meals_controller.rb
require 'rest-client'

class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :validate, :favorite, :select_diet, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    authorize Meal

    @meals = policy_scope(Meal)
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    authorize @meal
  end

  def validate
    authorize @meal

    result = RestClient.get "https://reqres.in/api/unknown/2"

    respond_to do |format|
      format.html { redirect_to @meal, notice: result }
      format.json { render :show, status: :validated, location: @meal }
    end
  end

  def favorite
    authorize @meal

    current_user.update meal_id: (@meal.favorite? current_user) ? nil : @meal.id

    respond_to do |format|
      format.html { redirect_to @meal, notice: (@meal.favorite? current_user) ? "This meal is now your favorite" : "This meal is now not your favorite" }
      format.json { render :show, status: :favorite, location: @meal }
    end
  end

  def select_diet
    authorize @meal

    current_user.update diet: @meal.category

    respond_to do |format|
      format.html { redirect_to @meal, notice: "This diet is now your personal diet" }
      format.json { render :show, status: :favorite, location: @meal }
    end
  end

  def unselect_diet
    authorize Meal

    current_user.update diet: nil

    respond_to do |format|
      format.html { redirect_to root_path, notice: "You have now no diet." }
      format.json { render :show, status: :favorite, location: @meal }
    end
  end

  # GET /meals/new
  def new
    @meal = Meal.new

    authorize @meal
  end

  # GET /meals/1/edit
  def edit
    authorize @meal
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    authorize @meal

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    authorize @meal

    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    authorize @meal

    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:name, :category, :desc)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage

  def index
    authorize :page

    if current_user
      authorize Meal

      @meals = policy_scope(Meal)
      @diets = @meals.select(:category)
    #   redirect_to dashboard_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title NabCooker
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    div class="container"
      - flash.each do | key, value |
        div class="alert alert-#{key}"
          = value

    = yield

app/views/meals/_diet.html.slim
table.table.table-hover
  thead
    tr
      th Name
      th Category
      th Desc

  tbody
    - @diets.each do |diet|
      tr data-link="#{unselect_diet_meals_path()}"
        td = diet.name + ((diet.favorite? current_user) ? " ⋆" : "")
        td = diet.category
        td = diet.desc

app/views/meals/_form.html.slim
= form_for @meal do |f|
  - if @meal.errors.any?
    #error_explanation
      h2 = "#{pluralize(@meal.errors.count, "error")} prohibited this meal from being saved:"
      ul
        - @meal.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :desc
    = f.text_area :desc
  .actions = f.submit

app/views/meals/_index.html.slim
table.table.table-hover
  thead
    tr
      th Name
      th Category
      th Desc

  tbody
    - @meals.each do |meal|
      tr data-link="#{meal_path(meal)}"
        td = meal.name + ((meal.favorite? current_user) ? " ⋆" : "")
        td = meal.category
        td = meal.desc

app/views/meals/edit.html.slim
h1 Editing meal

== render 'form'

=> link_to 'Show', @meal
'|
=< link_to 'Back', meals_path

app/views/meals/index.html.slim
h1 Listing meals

= render "index"

br

= link_to 'New Meal', new_meal_path

app/views/meals/new.html.slim
h1 New meal

== render 'form'

= link_to 'Back', meals_path

app/views/meals/show.html.slim
h2 = @meal.name + ((@meal.favorite? current_user) ? " ⋆" : "")
em = @meal.category
p
  = @meal.desc

= link_to "Validate", action: :validate
'|
- if @meal.favorite? current_user
  = link_to "Un-Favorite", action: :favorite
- else
  = link_to "Favorite", action: :favorite
'|
=< link_to 'Select diet', action: :select_diet
'|
=< link_to 'Back', root_path

app/views/pages/index.html.slim
h1 Welcome!

- if current_user
  ul
    li = link_to t("devise.links.profile").capitalize, edit_user_registration_path
    li = link_to t("devise.links.sign_out").capitalize, destroy_user_session_path, method: :delete

  = render "meals/index"
  - if current_user.diet
    em = "You current diet is #{current_user.diet}"
    '|
    = link_to "Diselect any diets.", controller: :meals, action: :unselect_diet
  - else
    em You currently have no diet.
- else
  p Please
  ul
    li = link_to t("devise.links.sign_in").capitalize, new_user_session_path
    li = link_to t("devise.links.sign_up").capitalize, new_user_registration_path